job_number: "J-25-XXXX"           # e.g., J-25-A134
job_folder_name: "J-25-XXXX (VSR)"
sterile: true                     # controls CoC template selection
run_data_root: "C:/path/to/S3D MFG PREP/2025 Run Data"
templates_map_path: "C:/path/to/S3D AI/AI Records/MBR Template Map.xlsx"
fake_825_root: "C:/path/to/S3D AI/AI Records/Empty Templates/Fake 825"
dropbox_root: ""                  # optional, can remain blank
cmd_rel_path: "CMD"               # subfolder under job folder
reset_sc_on_rerun: true           # re-copy S&C each run

